% Names67Occupations   1/29/14
%
% Names of the occupations, "brawn" variables, etc.

OccupationNames=[
'Home                                      '
'Executives, Administrative, and Managerial'
'Management Related                        '
'Architects                                '
'Engineers                                 '
'Math and Computer Science                 '
'Natural Science                           '
'Doctors                                   ' % Health Diagnosing
'Health Assessment                         '
'Therapists                                '
'Professors                                ' %Teachers, Postsecondary
'Teachers          Non-Postsecondary       '
'Librarians  and Curators                  '
'Social Scientists and Urban Planners      '
'Social Work                               '
'Lawyers       and Judges                  '
'Arts and Athletes                         '
'Health Technicians                        '
'Engineering Technicians                   '
'Science Technicians                       '
'Technicians, Other                        '
'Sales, all                                '
'Secretaries                               '
'Info. Clerks                              '
'Records Processing, Non-Financial         '
'Financial Records Processing              '
'Office Machine Operator                   '
'Computer/Communications Equip. Operator   '
'Mail Distribution                         '
'Scheduling and Distributing Clerks        '
'Adjusters and Investigators               '
'Misc. Admin Support                       '
'Private Household Occupations             '
'Firefighting                              '
'Police                                    '
'Guards                                    '
'Food Prep    and Service                  '
'Health Service                            '
'Cleaning and Building Service             '
'Personal Service                          '
'Farm Managers                             '
'Farm Work                                 '
'Related Agriculture                       '
'Forest, Logging, Fishers and Hunter       '
'Mechanics                                 ' %Vehicle
'Elec. Repairer                            '
'Misc. Repairer                            '
'Construction Trade                        '
'Extractive                                '
'Supervisor(P)                             ' % Precision supervisor
'Precision Metal                           '
'Precision Wood                            '
'Precision, Textile                        '
'Precision, Other                          '
'Precision, Food                           '
'Plant Operator                            '
'Metal and Plastic Machine Operator        '
'Metal and Plastic Processing Operator     '
'Woodworking Machine Operator              '
'Textile Machine Operator                  '
'Print Machine Operator                    '
'Machine Operator, Other                   '
'Fabricators                               '
'Production Inspectors                     '
'Motor Vehicle Operator                    '
'Non Motor Vehicle Operator                '
'Freight, Stock, Material Handler          '
];                                        


ShortNames={
'Home'
'Managers'
'MgmtRelated'
'Architects'
'Engineers'
'Math/CompSci'
'Science'
'Doctors'%HealthDiagnosing
'Nurses'
'Therapists'
'Professors'%Teachers,Postsecondary
'Teachers'
'Librarians'
'Soc.Scientists'
'SocialWork'
'Lawyers'
'Arts/Athletes'
'HealthTechs'
'Eng.Techs'
'ScienceTechs'
'OtherTechs'
'Sales'
'Secretaries'
'Info.Clerks'
'Records'
'FinancialClerk'
'OfficeMachine'
'ComputerTech'
'Mail'
'Clerks'
'Insurance'
'Misc.Admin'
'PrivateHshld'
'Firefighting'
'Police'
'Guards'
'FoodPrep'
'HealthService'
'Cleaning'
'PersonalService'
'FarmMgrs'
'FarmWork'
'Agriculture'
'Forest'
'Mechanics'%Vehicle
'Elec.Repairer'
'Misc.Repairer'
'Construction'
'Extractive'
'Supervisor(P)'%Precisionsupervisor
'MetalWork'
'WoodWork'
'Textiles'
'Other'
'Food'
'PlantOperator'
'MetalMach.'
'MetalProc.'
'WoodMach.'
'TextileMach.'
'PrintMach.'
'OtherMach.'
'Fabricators'
'Prod.Inspectors'
'MotorVehicle'
'OtherVehicle'
'Freight'
};



% Define BrawnyOccupations = 1 for "brawny" occs (mfg, firefighting, farm, etc)
% See Rendall-Brawniness-Index.xls spreadsheet
BrawnyOccupations=[
0 % 'Home'                                              
0 % 'Executives, Administrative, and Managerial'        
0 % 'Management Related'                                
0 % 'Architects'                                        
0 % 'Engineers '                                        
0 % 'Math and Computer Science '                        
0 % 'Natural Science '                                  
0 % 'Doctors ' % Health Diagnosing                      
0 % 'Health Assessment '                                
0 % 'Therapists'                                        
0 % 'Professors' %Teachers, Postsecondary               
0 % 'TeachersNon-Postsecondary '                        
0 % 'Librariansand Curators'                            
0 % 'Social Scientists and Urban Planners'              
0 % 'Social Work '                                      
0 % 'Lawyers and Judges'                                
0 % 'Arts and Athletes '                                
0 % 'Health Technicians'                                
0 % 'Engineering Technicians '                          
0 % 'Science Technicians '                              
0 % 'Technicians, Other'                                
0 % 'Sales, all'                                        
0 % 'Secretaries '                                      
0 % 'Info. Clerks'                                      
0 % 'Records Processing, Non-Financial '                
0 % 'Financial Records Processing'                      
0 % 'Office Machine Operator '                          
0 % 'Computer/Communications Equip. Operator '          
0 % 'Mail Distribution '                                
0 % 'Scheduling and Distributing Clerks'                
0 % 'Adjusters and Investigators '                      
0 % 'Misc. Admin Support '                              
0 % 'Private Household Occupations '                    
1 % 'Firefighting'                                      
1 % 'Police'                                            
1 % 'Guards'                                            
0 % 'Food Prepand Service'                              
0 % 'Health Service'                                    
1 % 'Cleaning and Building Service '                    
0 % 'Personal Service'                                  
1 % 'Farm Managers '                                    
1 % 'Farm Work '                                        
1 % 'Related Agriculture '                              
1 % 'Forest, Logging, Fishers and Hunter '              
1 % 'Mechanics ' %Vehicle                               
0 % 'Elec. Repairer'                                    
1 % 'Misc. Repairer'                                    
1 % 'Construction Trade'                                
1 % 'Extractive'                                        
1 % 'Supervisor(P) ' % Precision supervisor             
1 % 'Precision Metal '                                  
1 % 'Precision Wood'                                    
1 % 'Precision, Textile'                                
0 % 'Precision, Other'                                  
1 % 'Precision, Food '                                  
1 % 'Plant Operator'                                    
1 % 'Metal and Plastic Machine Operator'                
1 % 'Metal and Plastic Processing Operator '            
1 % 'Woodworking Machine Operator'                      
1 % 'Textile Machine Operator'                          
1 % 'Print Machine Operator'                            
1 % 'Machine Operator, Other '                          
1 % 'Fabricators '                                      
0 % 'Production Inspectors '                            
1 % 'Motor Vehicle Operator'                            
1 % 'Non Motor Vehicle Operator'                        
1 % 'Freight, Stock, Material Handler'                  
];
BrawnyOccupations=logical(BrawnyOccupations);

% T(i,g,Age) -- returns to experience
% From Erik, Jan 26, 2015 -- 
% As of Jan 2016, we are no longer using this. Chang has cohort-specific code in EsstimateTauZ.m
TigYMO_Erik=[
NaN      NaN     NaN   % 'Home'                                              
1.000	1.581	1.785  % 'Executives, Administrative, and Managerial'        
1.000	1.735	2.099  % 'Management Related'                                
1.000	1.871	2.387  % 'Architects'                                        
1.000	1.863	2.382  % 'Engineers '                                        
1.000	1.731	2.141  % 'Math and Computer Science '                        
1.000	1.812	2.168  % 'Natural Science '                                  
1.000	2.089	2.465  % 'Doctors ' % Health Diagnosing                      
1.000	1.999	2.708  % 'Health Assessment '                                
1.000	1.808	2.260  % 'Therapists'                                        
1.000	1.952	2.412  % 'Professors' %Teachers, Postsecondary               
1.000	1.904	2.469  % 'TeachersNon-Postsecondary '                        
1.000	1.752	2.113  % 'Librariansand Curators'                            
1.000	1.851	2.245  % 'Social Scientists and Urban Planners'              
1.000	1.770	2.174  % 'Social Work '                                      
1.000	2.207	2.769  % 'Lawyers and Judges'                                
1.000	1.713	2.095  % 'Arts and Athletes '                                
1.000	1.728	2.235  % 'Health Technicians'                                
1.000	1.752	2.338  % 'Engineering Technicians '                          
1.000	1.682	2.128  % 'Science Technicians '                              
1.000	1.791	2.298  % 'Technicians, Other'                                
1.000	1.597	1.871  % 'Sales, all'                                        
1.000	1.630	1.962  % 'Secretaries '                                      
1.000	1.675	2.111  % 'Info. Clerks'                                      
1.000	1.637	1.973  % 'Records Processing, Non-Financial '                
1.000	1.664	2.103  % 'Financial Records Processing'                      
1.000	1.571	1.893  % 'Office Machine Operator '                          
1.000	1.698	2.194  % 'Computer/Communications Equip. Operator '          
1.000	1.626	2.035  % 'Mail Distribution '                                
1.000	1.643	2.105  % 'Scheduling and Distributing Clerks'                
1.000	1.734	2.257  % 'Adjusters and Investigators '                      
1.000	1.639	2.005  % 'Misc. Admin Support '                              
1.000	1.546	1.882  % 'Private Household Occupations '                    
1.000	1.717	2.294  % 'Firefighting'                                      
1.000	1.688	2.164  % 'Police'                                            
1.000	1.560	1.835  % 'Guards'                                            
1.000	1.718	2.348  % 'Food Prepand Service'                              
1.000	1.616	1.997  % 'Health Service'                                    
1.000	1.523	1.809  % 'Cleaning and Building Service '                    
1.000	1.620	2.017  % 'Personal Service'                                  
1.000	1.485	1.661  % 'Farm Managers '                                    
1.000	1.517	1.871  % 'Farm Work '                                        
1.000	1.585	2.009  % 'Related Agriculture '                              
1.000	1.474	1.688  % 'Forest, Logging, Fishers and Hunter '              
1.000	1.598	2.007  % 'Mechanics ' %Vehicle                               
1.000	1.642	2.100  % 'Elec. Repairer'                                    
1.000	1.563	1.913  % 'Misc. Repairer'                                    
1.000	1.584	1.987  % 'Construction Trade'                                
1.000	1.558	1.932  % 'Extractive'                                        
1.000	1.581	1.923  % 'Supervisor(P) ' % Precision supervisor             
1.000	1.591	1.991  % 'Precision Metal '                                  
1.000	1.571	1.951  % 'Precision Wood'                                    
1.000	1.528	1.885  % 'Precision, Textile'                                
1.000	1.625	2.043  % 'Precision, Other'                                  
1.000	1.556	1.926  % 'Precision, Food '                                  
1.000	1.651	2.071  % 'Plant Operator'                                    
1.000	1.555	1.912  % 'Metal and Plastic Machine Operator'                
1.000	1.572	1.964  % 'Metal and Plastic Processing Operator '            
1.000	1.623	2.098  % 'Woodworking Machine Operator'                      
1.000	1.597	1.997  % 'Textile Machine Operator'                          
1.000	1.485	1.753  % 'Print Machine Operator'                            
1.000	1.511	1.797  % 'Machine Operator, Other '                          
1.000	1.576	1.965  % 'Fabricators '                                      
1.000	1.627	2.066  % 'Production Inspectors '                            
1.000	1.578	1.967  % 'Motor Vehicle Operator'                            
1.000	1.578	1.962  % 'Non Motor Vehicle Operator'                        
1.000	1.543	1.881  % 'Freight, Stock, Material Handler'                  
];


DecadeNames=[1960 1970 1980 1990 2000 2008]';
GroupNames={'White Men','White Women','Black Men','Black Women'};
WM=1; WW=2; BM=3; BW=4;

